service: aws-nodejs # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

functions: # add 4 functions for CRUD
  list:
    handler: handler.getList # point to exported create function in handler.js
    events:
      - http:
          path: list # path will be domain.name.com/dev/notes
          method: get
          cors: true
# serverless offline plugin
plugins:
  - serverless-offline
